version: "2"

services:
    db:
        extends:
            file: base.yml
            service: db

    app:
        extends:
            file: base.yml
            service: app
        build:
            args:
                - DJANGO_ENV=dev
        command: python ./app/manage.py runserver 0.0.0.0:8000
        volumes:
            - ./django_app:/app
        ports:
            - "8000:8000"
        depends_on:
            - db

volumes:
    db_data:
        external: true
