# Generated by Django 2.0 on 2018-06-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id_extension', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('extension', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('numero_telefono', models.CharField(max_length=8)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Extension')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Reservante'),
        ),
    ]
